dist: bionic
language: python
cache: pip

addons:
  apt:
    packages:
      - rabbitmq-server

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install .[rmq,dev]
  - pip install flake8
  - pip install codecov # Not included in requirements so install here

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  - pytest --cov=kiwipy test

after_success:
  - coverage report
  - codecov

jobs:
  include:
    - stage: docs-test
      python: 3.6
      install:
        - pip install .[rmq,dev,docs]
        - pip install flake8
      script:
        - sphinx-build -nT -b dummy docs/source build/html
